name: Pull Request Webhook

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send PR Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
            "repository_owner": "${{ github.repository_owner }}",
            "repository_name": "${{ github.event.repository.name }}",
            "pull_request_number": ${{ github.event.pull_request.number }},
            "pull_request_url": "${{ github.event.pull_request.html_url }}",
            "action": "${{ github.event.action }}", 
            "pull_request_title": "${{ github.event.pull_request.title }}",
            "pull_request_author": "${{ github.event.pull_request.user.login }}"
          }' \
          "http://n8n.choyoonseo.com/webhook/eabf283d-4b39-4e20-a9a1-edc7db81daf7/webhook"
